"""empty message

Revision ID: 751df00acae4
Revises: 3b021ecb12f0
Create Date: 2021-01-08 18:21:00.875837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751df00acae4'
down_revision = '3b021ecb12f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todolists SET completed = False WHERE completed IS NULL;')
    op.alter_column('todolists', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
